### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by FrancescAlted** [statkraft/shyft#111]
I am trying to compile the master version in the repo, and I'm getting this error:

```
/home/faltet/uio/shyft/test/main.cpp: In member function ‘virtual void TestDescription_suite_cell_builder_test_test_build_geo_cell_data_from_geo_region_data::runTest()’:
/home/faltet/uio/shyft/test/main.cpp:551:43: error: ‘class cell_builder_test’ has no member named ‘test_build_geo_cell_data_from_geo_region_data’
  void runTest() { suite_cell_builder_test.test_build_geo_cell_data_from_geo_region_data(); }
                                           ^
make[2]: *** [test/CMakeFiles/test_shyft.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [test/CMakeFiles/test_shyft.dir/all] Error 2
make: *** [all] Error 2
```

I have searched for a `test_build_geo_cell_data_from_geo_region_data` string in the whole repo, but I cannot find it.  Any hints?

I am on a Debian 16.04 box, using latest Miniconda and Python 3.5.

**Comment by sigbjorn** [comment]
Hi,

I guess somehow your master source is out dated (weird, but only
explanation before starting check).

I will run a build on linux 16.04 now just to be sure.
Br Sigbjørn

**Comment by FrancescAlted** [comment]
Well, I now that I remember, I pulled from master just today, so perhaps it is a stale file.  I am going to clone into a fresh directory and report back.

**Comment by FrancescAlted** [comment]
Bingo.  After cloning into a fresh directory, I was able to compile everything without this problem.  Lesson to learn: after a large period of time, always do `git clean -fx` before pulling new stuff.

**Comment by sigbjorn** [comment]
Thnx!
